### ISSUE TITLE
How to suppress errors: HTML Guard sees you!

### ISSUE THREAD

**Issue by kelilive** [DosX-dev/HTML-Guard#1]
Do these errors make people feel unreliable and have the potential to inhibit? Thank you.

**Comment by DosX-dev** [comment]
Hello! This is a humorous message displayed by HTML Guard to show the user that their opening of developer tools is unauthorized and is provided for by the site's protective mechanisms.
This does not affect the functionality of the site in any way.

**Comment by kelilive** [comment]
How should I disable it? By modifying the code, because I don't want the page to have an error code.
